### ISSUE TITLE
can we use this for feeder bot or can you include lib

### ISSUE THREAD

**Issue by ghost** [Mat2095/MySlither#1]

**Comment by Mat2095** [comment]
In theory you can, however the bot-layer is not even started and you would have to find a way to allow multiple connections. This is not my goal, so I won't implement that, but that doesn't mean you can't do it.
You can just download the lib from here: https://github.com/TooTallNate/Java-WebSocket/releases/tag/Java-WebSocket-1.3.0 , it is released under an MIT license, so I would have to include that license within the GUI if I would include the lib. I will do so for release-versions, but until then I don't see the need for it.

**Comment by ghost** [comment]
can i use it with rattle snake

**Comment by ghost** [comment]
can you help me

**Comment by Mat2095** [comment]
I don't understand your question, RattleSnake and this are both Slither-clients, one in JavaScript one in Java. How would use use them together? This makes no sense.

**Comment by ghost** [comment]
but this has no server

**Comment by ghost** [comment]
can i get your skype

**Comment by ghost** [comment]
i wanted to ask which is better this or that

**Comment by Mat2095** [comment]
Neither has RattleSnake. 
I haven't tried RattleSnake, basically because I'm not good at JS and also don't really like JS, but why don't you just try both?

**Comment by ghost** [comment]
but how do i implement this

**Comment by Mat2095** [comment]
Implement what?

**Comment by ghost** [comment]
like how to use this to make bots

**Comment by ghost** [comment]
cuz im not good at java

**Comment by Mat2095** [comment]
Then for you RattleSnake is better, assuming you are better in JS than in Java.

**Comment by ghost** [comment]
but i want to test this

**Comment by Mat2095** [comment]
Then do so.
